services:
  - type: web
    name: backup-stream
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PASSWORD
        sync: false
      - key: RTMP_URL
        sync: false
      - key: STREAM_KEY
        sync: false
